In [ ]:
import pymysql
import pandas as pd

In [ ]:
conn=pymysql.connect(host='localhost',port=int(3306),user='root',passwd='*****',db='test')

df=pd.read_sql_query("SELECT * FROM chat ",conn)


print(df)

   user_id  thread_id  id                                               body
0        1        101   1               I am glad to be a part of this team.
1        2        102   2  That approach could me made easier if we use t...
2        1        103   3                I agree and I totally support that.


In [ ]:
conn=pymysql.connect(host='localhost',port=int(3306),user='root',passwd='*****',db='test')
test=pd.read_sql_query("select user_id,group_concat(body) as TEXT from chat group by user_id ",conn)
print(test)

   user_id                                               TEXT
0        1  I am glad to be a part of this team.,I agree a...
1        2  That approach could me made easier if we use t...


In [ ]:
from IPython.core.debugger import set_trace

#%load_ext nb_black

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import time

plt.style.use(style="seaborn")
%matplotlib inline

In [ ]:
def mbti_to_big5(mbti):
   
  
    mbti = mbti.lower()
    cEXT, cNEU, cAGR, cCON, cOPN = 0,np.NaN,0,0,0
    if mbti[0] == "i":
        cEXT = 0
    elif mbti[0] == "e":
        cEXT = 1

    
    if mbti[1] == "n":
        cOPN = 1
    elif mbti[1] == "s":
        cOPN = 0   

    
    if mbti[2] == "t":
        cAGR = 0
    elif mbti[2] == "f":
        cAGR = 1

    if mbti[3] == "p":
        cCON = 0
    elif mbti[3] == "j":
        cCON = 1

    return cEXT, cNEU, cAGR, cCON, cOPN

In [ ]:
df_essays =pd.read_csv('essays.csv', encoding='cp1252', delimiter=',', quotechar='"')

In [ ]:
for e in df_essays.columns[2:7]:
    df_essays[e] = df_essays[e].replace('n', '0')
    df_essays[e] = df_essays[e].replace('y', '1')
    
    df_essays[e] = pd.to_numeric(df_essays[e])

In [ ]:
df_essays.head()

#AUTHID                                               TEXT  cEXT  \
0  1997_504851.txt  Well, right now I just woke up from a mid-day ...     0   
1  1997_605191.txt  Well, here we go with the stream of consciousn...     0   
2  1997_687252.txt  An open keyboard and buttons to push. The thin...     0   
3  1997_568848.txt  I can't believe it!  It's really happening!  M...     1   
4  1997_688160.txt  Well, here I go with the good old stream of co...     1   

   cNEU  cAGR  cCON  cOPN  
0     1     1     0     1  
1     0     1     0     0  
2     1     0     1     1  
3     0     1     1     0  
4     0     1     0     1

In [ ]:
test.head()

user_id                                               TEXT
0        1  I am glad to be a part of this team.,I agree a...
1        2  That approach could me made easier if we use t...

In [ ]:
df_kaggle = pd.read_csv('mbti_1.csv',  skiprows=0 )

df_kaggle["cEXT"] =   df_kaggle.apply(lambda x: mbti_to_big5(x.type)[0], 1)
df_kaggle["cNEU"] =   df_kaggle.apply(lambda x: mbti_to_big5(x.type)[1], 1)
df_kaggle["cAGR"] =   df_kaggle.apply(lambda x: mbti_to_big5(x.type)[2], 1)
df_kaggle["cCON"] =   df_kaggle.apply(lambda x: mbti_to_big5(x.type)[3], 1)
df_kaggle["cOPN"] =   df_kaggle.apply(lambda x: mbti_to_big5(x.type)[4], 1)

df_kaggle = df_kaggle[["posts", "cEXT", "cNEU", "cAGR", "cCON", "cOPN"]]
df_kaggle.columns = ["TEXT", "cEXT", "cNEU", "cAGR", "cCON", "cOPN"]

# remove |||
df_kaggle["TEXT"] = df_kaggle.apply(lambda x: x.TEXT.replace("|||", " ")[:], 1)


df_kaggle

TEXT  cEXT  cNEU  cAGR  \
0     'http://www.youtube.com/watch?v=qsXHcwe3krw ht...     0   NaN     1   
1     'I'm finding the lack of me in these posts ver...     1   NaN     0   
2     'Good one  _____   https://www.youtube.com/wat...     0   NaN     0   
3     'Dear INTP,   I enjoyed our conversation the o...     0   NaN     0   
4     'You're fired. That's another silly misconcept...     1   NaN     0   
...                                                 ...   ...   ...   ...   
8670  'https://www.youtube.com/watch?v=t8edHB_h908 I...     0   NaN     1   
8671  'So...if this thread already exists someplace ...     1   NaN     1   
8672  'So many questions when i do these things.  I ...     0   NaN     0   
8673  'I am very conflicted right now when it comes ...     0   NaN     1   
8674  'It has been too long since I have been on per...     0   NaN     1   

      cCON  cOPN  
0        1     1  
1        0     1  
2        0     1  
3        1     1  
4        1     1  
...    ...   ...  
8670     0     0  
8671     0     1  
8672     0     1  
8673     0     1  
8674     0     1  

[8675 rows x 6 columns]

In [ ]:
#concatinate the dataframes:
frames  = [df_essays, df_kaggle]
essay = pd.concat(frames, sort=False)
essay.reset_index(drop=True)



print("saved entries: ", len(essay))

saved entries:  11142


In [ ]:
essay

#AUTHID                                               TEXT  \
0     1997_504851.txt  Well, right now I just woke up from a mid-day ...   
1     1997_605191.txt  Well, here we go with the stream of consciousn...   
2     1997_687252.txt  An open keyboard and buttons to push. The thin...   
3     1997_568848.txt  I can't believe it!  It's really happening!  M...   
4     1997_688160.txt  Well, here I go with the good old stream of co...   
...               ...                                                ...   
8670              NaN  'https://www.youtube.com/watch?v=t8edHB_h908 I...   
8671              NaN  'So...if this thread already exists someplace ...   
8672              NaN  'So many questions when i do these things.  I ...   
8673              NaN  'I am very conflicted right now when it comes ...   
8674              NaN  'It has been too long since I have been on per...   

      cEXT  cNEU  cAGR  cCON  cOPN  
0        0   1.0     1     0     1  
1        0   0.0     1     0     0  
2        0   1.0     0     1     1  
3        1   0.0     1     1     0  
4        1   0.0     1     0     1  
...    ...   ...   ...   ...   ...  
8670     0   NaN     1     0     0  
8671     1   NaN     1     0     1  
8672     0   NaN     0     0     1  
8673     0   NaN     1     0     1  
8674     0   NaN     1     0     1  

[11142 rows x 7 columns]

Remove URLs and HTML

In [ ]:
import re


def remove_URL(text):
    url = re.compile(r"https?://\S+|www\.\S+")
    return url.sub(r"", text)


def remove_html(text):
    html = re.compile(r"<.*?>")
    return html.sub(r"", text)

In [ ]:
def remove_emoji(string):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub(r"", string)

Remove punctuation

In [ ]:
import string


def remove_punct(text):
    table = str.maketrans("", "", string.punctuation)
    return text.translate(table)

In [ ]:
essay["TEXT"] = essay.TEXT.map(lambda x: remove_URL(x))
essay["TEXT"] = essay.TEXT.map(lambda x: remove_html(x))
essay["TEXT"] = essay.TEXT.map(lambda x: remove_emoji(x))
essay["TEXT"] = essay.TEXT.map(lambda x: remove_punct(x))

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nikit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

Remove stopwords

In [ ]:
from nltk.corpus import stopwords

stop = set(stopwords.words("english"))


def remove_stopwords(text):
    text = [word.lower() for word in text.split() if word.lower() not in stop]

    return " ".join(text)

In [ ]:
essay["TEXT"] = essay["TEXT"].map(remove_stopwords)

In [ ]:
essay.TEXT 

0       well right woke midday nap sort weird ever sin...
1       well go stream consciousness essay used things...
2       open keyboard buttons push thing finally worke...
3       cant believe really happening pulse racing lik...
4       well go good old stream consciousness assignme...
                              ...                        
8670    ixfp always think cats fi doms reason especial...
8671    soif thread already exists someplace else heck...
8672    many questions things would take purple pill p...
8673    conflicted right comes wanting children honest...
8674    long since personalitycafe although doesnt see...
Name: TEXT, Length: 11142, dtype: object

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nikit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
from nltk.tokenize import word_tokenize
import nltk


def create_corpus_tk(df):
    corpus = []
    for text in essay["TEXT"]:
        words = [word.lower() for word in word_tokenize(text)]
        corpus.append(words)
    return corpus

In [ ]:
corpus = create_corpus_tk(essay)

In [ ]:
num_words = len(corpus)
print(num_words)

11142


Train / test split

In [ ]:
train_size = int(essay.shape[0] * 0.8)

train_sentences = essay.TEXT[:train_size]
train_labels_cEXT = essay.cEXT[:train_size]
train_labels_cAGR = essay.cAGR[:train_size]
train_labels_cCON = essay.cCON[:train_size]
train_labels_cOPN = essay.cOPN[:train_size]

test_sentences = essay.TEXT[train_size:]
test_labels_cEXT = essay.cEXT[train_size:]
test_labels_cAGR = essay.cAGR[train_size:]
test_labels_cCON = essay.cCON[train_size:]
test_labels_cOPN = essay.cOPN[train_size:]

In [ ]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

max_len = 50

In [ ]:
tokenizer = Tokenizer(num_words=num_words)
tokenizer.fit_on_texts(train_sentences)

In [ ]:
train_sequences = tokenizer.texts_to_sequences(train_sentences)

In [ ]:
train_sentences

0       well right woke midday nap sort weird ever sin...
1       well go stream consciousness essay used things...
2       open keyboard buttons push thing finally worke...
3       cant believe really happening pulse racing lik...
4       well go good old stream consciousness assignme...
                              ...                        
6441    im sure whats better posting individual pictur...
6442    im well second year didnt finish last year im ...
6443    agree except jessica chastain believe enfj hig...
6444    always take much think reasonable wham never t...
6445    wow dude really spoton im energized people get...
Name: TEXT, Length: 8913, dtype: object

In [ ]:
train_sequences

In [ ]:
train_padded = pad_sequences(
    train_sequences, maxlen=max_len, truncating="post", padding="post"
)

In [ ]:
train_padded

array([[  15,   37, 1948, ...,   90,   54,    6],
       [  15,   23, 1260, ...,  162, 1375, 1243],
       [ 369, 2349, 4717, ...,  734,   84,    7],
       ...,
       [ 135,  467, 5594, ...,   42, 2241,  474],
       [  27,   60,   13, ...,   78,  460,  688],
       [ 322, 1019,    6, ...,  577,   21, 1167]])

In [ ]:
test_sequences = tokenizer.texts_to_sequences(test_sentences)
test_padded = pad_sequences(
    test_sequences, maxlen=max_len, padding="post", truncating="post"
)

In [ ]:
test_padded

array([[  17,   21, 1199, ...,    2,  783, 4069],
       [ 664,  514,  943, ...,   74,   46,   53],
       [4237,  796,  126, ...,  386, 1958,  453],
       ...,
       [  56,  341,   18, ..., 1206,   28,   89],
       [6614,   37,  238, ..., 2203,  151, 1291],
       [  83,   87, 5396, ...,   70,  137, 2809]])

In [ ]:
word_index = tokenizer.word_index
print("Number of unique words:", len(word_index))

Number of unique words: 140867


In [ ]:
word_index

Create the Embedding dictionary

In [ ]:
embedding_dict = {}
with open("glove.6B.50d.txt", "r",encoding="utf8") as f:
    for line in f:
        values = line.split()
        word = values[0]
        vectors = np.asarray(values[1:], "float32")
        embedding_dict[word] = vectors
f.close()

In [ ]:
embedding_dict

In [ ]:
num_words = len(word_index) + 1
embedding_matrix = np.zeros((num_words, 50))

for word, i in word_index.items():
    if i < num_words:
        emb_vec = embedding_dict.get(word)
        if emb_vec is not None:
            embedding_matrix[i] = emb_vec

In [ ]:
embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.067678  ,  0.51832002,  1.32599998, ..., -0.65103   ,
         0.12924001,  0.48723999],
       [ 0.36807999,  0.20834   , -0.22318999, ..., -0.67236   ,
        -0.39708999,  0.25183001],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-1.02339995, -0.50840002, -1.67120004, ..., -1.65760005,
        -0.31445   ,  0.14918   ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
print(train_padded.shape)
print(train_labels_cEXT.shape)

(8913, 50)
(8913,)


In [ ]:
print(test_padded.shape)
print(test_labels_cEXT.shape)

(2229, 50)
(2229,)


In [ ]:
import tensorflow as tf

In [ ]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, Dropout
from keras.initializers import Constant
from keras.optimizers import Adam

model = Sequential()

model.add(
    Embedding(
        num_words,
        50,
        embeddings_initializer=Constant(embedding_matrix),
        #tf.nn.embedding_lookup(num_words,embedding_matrix),
        input_length=max_len,
        trainable=False,
    )
)

model.add(LSTM(50, dropout=0.1))
model.add(Dense(1, activation="sigmoid"))


optimizer = Adam(learning_rate=3e-4)

model.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

In [ ]:
history = model.fit(
    train_padded,
    train_labels_cEXT,
    epochs=20,
    validation_data=(test_padded, test_labels_cEXT),

    verbose=1,
)

Epoch 1/20
279/279 [==============================] - 7s 18ms/step - loss: 0.6325 - accuracy: 0.6772 - val_loss: 0.5506 - val_accuracy: 0.7734
Epoch 2/20
279/279 [==============================] - 5s 17ms/step - loss: 0.6103 - accuracy: 0.6851 - val_loss: 0.5504 - val_accuracy: 0.7676
Epoch 3/20
279/279 [==============================] - 5s 18ms/step - loss: 0.5962 - accuracy: 0.7007 - val_loss: 0.5488 - val_accuracy: 0.7721
Epoch 4/20
279/279 [==============================] - 6s 20ms/step - loss: 0.5971 - accuracy: 0.6930 - val_loss: 0.5444 - val_accuracy: 0.7681
Epoch 5/20
279/279 [==============================] - 6s 22ms/step - loss: 0.5894 - accuracy: 0.7029 - val_loss: 0.5424 - val_accuracy: 0.7694
Epoch 6/20
279/279 [==============================] - 7s 23ms/step - loss: 0.5970 - accuracy: 0.6972 - val_loss: 0.5333 - val_accuracy: 0.7734
Epoch 7/20
279/279 [==============================] - 6s 23ms/step - loss: 0.5847 - accuracy: 0.7079 - val_loss: 0.5535 - val_accuracy: 0.7595

In [ ]:
model3 = Sequential()

model3.add(
    Embedding(
        num_words,
        50,
        embeddings_initializer=Constant(embedding_matrix),
        #tf.nn.embedding_lookup(num_words,embedding_matrix),
        input_length=max_len,
        trainable=False,
    )
)
    
model3.add(LSTM(50, dropout=0.1))
model3.add(Dense(1, activation="sigmoid"))


optimizer = Adam(learning_rate=3e-4)

model3.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

In [ ]:
history = model3.fit(
    train_padded,
    train_labels_cAGR,
    epochs=20,
    validation_data=(test_padded, test_labels_cAGR),

    verbose=1,
)

Epoch 1/20
279/279 [==============================] - 8s 23ms/step - loss: 0.6919 - accuracy: 0.5333 - val_loss: 0.6830 - val_accuracy: 0.5653
Epoch 2/20
279/279 [==============================] - 6s 20ms/step - loss: 0.6868 - accuracy: 0.5408 - val_loss: 0.6753 - val_accuracy: 0.5873
Epoch 3/20
279/279 [==============================] - 6s 21ms/step - loss: 0.6776 - accuracy: 0.5733 - val_loss: 0.6563 - val_accuracy: 0.6124
Epoch 4/20
279/279 [==============================] - 6s 22ms/step - loss: 0.6714 - accuracy: 0.5876 - val_loss: 0.6560 - val_accuracy: 0.6151
Epoch 5/20
279/279 [==============================] - 6s 22ms/step - loss: 0.6634 - accuracy: 0.6016 - val_loss: 0.6548 - val_accuracy: 0.6231
Epoch 6/20
279/279 [==============================] - 6s 22ms/step - loss: 0.6619 - accuracy: 0.6004 - val_loss: 0.6586 - val_accuracy: 0.6083
Epoch 7/20
279/279 [==============================] - 6s 22ms/step - loss: 0.6604 - accuracy: 0.5995 - val_loss: 0.6467 - val_accuracy: 0.6281

In [ ]:
model4 = Sequential()

model4.add(
    Embedding(
        num_words,
        50,
        embeddings_initializer=Constant(embedding_matrix),
        #tf.nn.embedding_lookup(num_words,embedding_matrix),
        input_length=max_len,
        trainable=False,
    )
)
    

model4.add(LSTM(50, dropout=0.1))
model4.add(Dense(1, activation="sigmoid"))


optimizer = Adam(learning_rate=3e-4)

model4.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

In [ ]:
history = model4.fit(
    train_padded,
    train_labels_cCON,
    epochs=20,
    validation_data=(test_padded, test_labels_cCON),

    verbose=1,
)

Epoch 1/20
279/279 [==============================] - 8s 23ms/step - loss: 0.6892 - accuracy: 0.5491 - val_loss: 0.6724 - val_accuracy: 0.5980
Epoch 2/20
279/279 [==============================] - 6s 21ms/step - loss: 0.6788 - accuracy: 0.5730 - val_loss: 0.6695 - val_accuracy: 0.5971
Epoch 3/20
279/279 [==============================] - 6s 22ms/step - loss: 0.6781 - accuracy: 0.5683 - val_loss: 0.6683 - val_accuracy: 0.6021
Epoch 4/20
279/279 [==============================] - 6s 22ms/step - loss: 0.6708 - accuracy: 0.5928 - val_loss: 0.6681 - val_accuracy: 0.5877
Epoch 5/20
279/279 [==============================] - 7s 23ms/step - loss: 0.6676 - accuracy: 0.5961 - val_loss: 0.6659 - val_accuracy: 0.5944
Epoch 6/20
279/279 [==============================] - 6s 23ms/step - loss: 0.6659 - accuracy: 0.5919 - val_loss: 0.6663 - val_accuracy: 0.6007
Epoch 7/20
279/279 [==============================] - 6s 23ms/step - loss: 0.6662 - accuracy: 0.6008 - val_loss: 0.6652 - val_accuracy: 0.6016

In [ ]:
model5 = Sequential()

model5.add(
    Embedding(
        num_words,
        50,
        embeddings_initializer=Constant(embedding_matrix),
        #tf.nn.embedding_lookup(num_words,embedding_matrix),
        input_length=max_len,
        trainable=False,
    )
)

model5.add(LSTM(50, dropout=0.1))
model5.add(Dense(1, activation="sigmoid"))


optimizer = Adam(learning_rate=3e-4)

model5.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

In [ ]:
history = model5.fit(
    train_padded,
    train_labels_cOPN,
    epochs=20,
    validation_data=(test_padded, test_labels_cOPN),

    verbose=1,
)

Epoch 1/20
279/279 [==============================] - 8s 23ms/step - loss: 0.5663 - accuracy: 0.7416 - val_loss: 0.4146 - val_accuracy: 0.8591
Epoch 2/20
279/279 [==============================] - 6s 23ms/step - loss: 0.5062 - accuracy: 0.7638 - val_loss: 0.4064 - val_accuracy: 0.8605
Epoch 3/20
279/279 [==============================] - 7s 26ms/step - loss: 0.4994 - accuracy: 0.7692 - val_loss: 0.4035 - val_accuracy: 0.8605
Epoch 4/20
279/279 [==============================] - 7s 23ms/step - loss: 0.4823 - accuracy: 0.7808 - val_loss: 0.4043 - val_accuracy: 0.8582
Epoch 5/20
279/279 [==============================] - 7s 24ms/step - loss: 0.4951 - accuracy: 0.7721 - val_loss: 0.4125 - val_accuracy: 0.8524
Epoch 6/20
279/279 [==============================] - 6s 22ms/step - loss: 0.4905 - accuracy: 0.7722 - val_loss: 0.4121 - val_accuracy: 0.8528
Epoch 7/20
279/279 [==============================] - 6s 22ms/step - loss: 0.4857 - accuracy: 0.7741 - val_loss: 0.4054 - val_accuracy: 0.8578

In [ ]:
sequences = tokenizer.texts_to_sequences(test.TEXT)
padded = pad_sequences(sequences, maxlen=max_len, padding="post", truncating="post")

In [ ]:
pred = model.predict(padded)
pred_int = pred.round().astype("int")

In [ ]:
pred4 = model4.predict(padded)
pred_int4 = pred4.round().astype("int")

In [ ]:
pred3 = model3.predict(padded)
pred_int3 = pred3.round().astype("int")

In [ ]:
pred5 = model5.predict(padded)
pred_int5 = pred5.round().astype("int")

In [ ]:
pred

array([[0.486046  ],
       [0.48744595]], dtype=float32)

In [ ]:
pred_int.T

array([[0, 0]])

In [ ]:
test['cEXT'] = pred_int

In [ ]:
test['cAGR'] = pred_int3

In [ ]:
test['cCON'] = pred_int4

In [ ]:
test['cOPN'] = pred_int5

In [ ]:
test.head(25)

user_id                                               TEXT  cEXT  cAGR  \
0        1  I am glad to be a part of this team.,I agree a...     0     1   
1        2  That approach could me made easier if we use t...     0     0   

   cCON  cOPN  
0     0     1  
1     0     1

In [ ]:
#saving the predicted values to a .csv file 
test.to_csv('final.csv', index=False)